Flashdriver and rustBoot support was added for stm32f334 board  and conflicts resolved
nihalpasham/rustBoot pull request #40
Opened 2022-06-27 13:19 UTC by sarath3192

#20  New board added
```
Command : cargo stm32f334 build rustBoot-only
```
sarathk@sarath:~/stm32f/PULL_REQUEST/rustBoot$ cargo stm32f334 build rustBoot-only
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/xtask stm32f334 build rustBoot-only`
$ cargo build --release
   Compiling version_check v0.9.4
   Compiling autocfg v1.1.0
   Compiling typenum v1.15.0
   ...
   ...
   Comp
   Compiling ecdsa v0.13.4
   Compiling p256 v0.10.1
   Compiling rustBoot v0.1.0 (/home/sarathk/stm32f/PULL_REQUEST/rustBoot/rustBoot)
   Compiling rustBoot-hal v0.1.0 (/home/sarathk/stm32f/PULL_REQUEST/rustBoot/boards/hal)
   Compiling rustBoot-update v0.1.0 (/home/sarathk/stm32f/PULL_REQUEST/rustBoot/boards/update)
    Finished release [optimized] target(s) in 1m 38s

```
Command : cargo stm32f334 build pkgs-for
```
sarathk@sarath:~/stm32f/PULL_REQUEST/rustBoot$ cargo stm32f334 build pkgs-for
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/xtask stm32f334 build pkgs-for`
$ cargo build --release
   Compiling panic-probe v0.3.0
   Compiling stm32f334_bootfw v0.1.0 (/home/sarathk/stm32f/PULL_REQUEST/rustBoot/boards/firmware/stm32f334/boot_fw_blinky_green)
    Finished release [optimized] target(s) in 1.79s
$ cargo build --release
   Compiling stm32f334_updtfw v0.1.0 (/home/sarathk/stm32f/PULL_REQUEST/rustBoot/boards/firmware/stm32f334/updt_fw_blinky_red)
    Finished release [optimized] target(s) in 1.13s
$ cargo build --release
    Finished release [optimized] target(s) in 0.15s

```
Command : cargo stm32f334 sign pkgs-for
```
sarathk@sarath:~/stm32f/PULL_REQUEST/rustBoot$ cargo stm32f334 sign pkgs-for
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/xtask stm32f334 sign pkgs-for`
$ python3 convert2bin.py
$ python3 signer.py
['sign.py', '--ecc256', '--sha256', 'stm32f334_updtfw.bin', 'ecc256.der', '1235']
Update type:          Firmware
Input image:          stm32f334_updtfw.bin
Selected cipher:      ecc256
Public key:           ecc256.der
Output image:         stm32f334_updtfw_v1235_signed.bin
Not Encrypted
Calculating sha256 digest...
Signing the firmware...
Done.
Output image successfully created.
['sign.py', '--ecc256', '--sha256', 'stm32f334_bootfw.bin', 'ecc256.der', '1234']
Update type:          Firmware
Input image:          stm32f334_bootfw.bin
Selected cipher:      ecc256
Public key:           ecc256.der
Output image:         stm32f334_bootfw_v1234_signed.bin
Not Encrypted
Calculating sha256 digest...
Signing the firmware...
Done.
Output image successfully created.

2022-06-27 13:21 UTC, imrank03 commented on .github/workflows/ci.yml
> +          cargo +nightly test --package rustBoot --lib --features stm32f746 -- parser::tests --nocapture
Remove this line

2022-06-27 13:28 UTC, imrank03 requested changes
Remove binaries

2022-06-27 13:33 UTC, imrank03 approved these changes

2022-06-28 04:36 UTC, nihalpasham approved these changes

2022-06-28 04:37 UTC, nihalpasham commented
looks good. 🦸🏾

2022-06-28 05:53 UTC, merged